Update nixos.py
Super quick fix; since the `nixos` function doesn't have a parameter for the `yes` click option, this command always blows up with `TypeError: nixos() got an unexpected keyword argument 'yes'`. This commit adds the missing parameter.